costmap/costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 15.0
    publish_frequency: 10.0
    resolution: 0.1
    rolling_window: true
    width: 5
    height: 30
    origin_x: 0.0
    origin_y: 0.0
    plugins: 
      - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}

    obstacle_layer:
      enabled: true
      observation_sources: pointcloud_sensor
      pointcloud_sensor: 
        data_type: PointCloud2
        topic: /gen0_model/front3d/lidar/points
        marking: true
        clearing: true
        max_obstacle_height: 5.0
        obstacle_range: 15.0
        raytrace_range: 15.0
