costmap/costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    rolling_window: true
    width: 10
    height: 10
    origin_x: -5.0
    origin_y: -5.0
    plugins: 
      - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

    static_layer:
      enabled: false 

    obstacle_layer:
      enabled: true
      observation_sources: laser_scan_sensor
      laser_scan_sensor: 
        data_type: LaserScan
        topic: /gen0_model/fr/lidar/scan
        marking: true
        clearing: true
        max_obstacle_height: 2.0
        obstacle_range: 2.5
        raytrace_range: 3.0

    inflation_layer:
      enabled: true
      inflation_radius: 0.5
      cost_scaling_factor: 10.0
