<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_steering_robot">

  <xacro:property name="wheel_base" value="2.8"/>
  <xacro:property name="wheel_track" value="1.385"/>
  <xacro:property name="wheel_radius" value="0.3"/>
  <xacro:property name="max_steering_angle" value="0.31"/>
  <xacro:property name="min_steering_angle" value="-0.31"/>

  <material name="white">
      <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
  </material>

  <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
  </material>

  <material name="black">
      <color rgba="0 0 0 1"/>
  </material>

  <material name="red">
      <color rgba="1 0 0 1"/>
  </material>

  <!-- Define robot links -->
  <link name="chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1 1 1"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <link name="front_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <link name="front_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <link name="rear_left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <link name="rear_right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <!-- Define robot joints -->
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="front_left_wheel"/>
    <origin xyz="${wheel_base/2} ${-wheel_track/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="front_right_wheel"/>
    <origin xyz="${wheel_base/2} ${wheel_track/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

 <joint name="front_left_steering_joint" type="revolute">
  <parent link="chassis"/>
  <child link="front_left_wheel"/>
  <origin xyz="${wheel_base/2} ${-wheel_track/2} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit effort="100" lower="${min_steering_angle}" upper="${max_steering_angle}" />
  <limit lower="${min_steering_angle}" upper="${max_steering_angle}">
    <effort value="100"/>
  </limit>
</joint>

<joint name="front_right_steering_joint" type="revolute">
  <parent link="chassis"/>
  <child link="front_right_wheel"/>
  <origin xyz="${wheel_base/2} ${wheel_track/2} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${min_steering_angle}" upper="${max_steering_angle}">
    <effort value="100"/>
  </limit>
</joint>

<joint name="rear_left_steering_joint" type="revolute">
  <parent link="chassis"/>
  <child link="rear_left_wheel"/>
  <origin xyz="${-wheel_base/2} ${-wheel_track/2} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${min_steering_angle}" upper="${max_steering_angle}">
    <effort value="100"/>
  </limit>
</joint>

<joint name="rear_right_steering_joint" type="revolute">
  <parent link="chassis"/>
  <child link="rear_right_wheel"/>
  <origin xyz="${-wheel_base/2} ${wheel_track/2} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${min_steering_angle}" upper="${max_steering_angle}">
    <effort value="100"/>
  </limit>
</joint>

</robot>

