4ws:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint3_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: front_left_wheel_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint4_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: front_right_wheel_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}


  front_left_steering_position_controller:
    type: position_controllers/JointPositionController
    joint: front_left_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_right_steering_position_controller:
    type: position_controllers/JointPositionController
    joint: front_right_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



  back_left_steering_position_controller:
    type: position_controllers/JointPositionController
    joint: back_left_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  back_right_steering_position_controller:
    type: position_controllers/JointPositionController
    joint: back_right_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
