

footprint: [ [-2.2,-1.05], [2.2,-1.05], [2.2, 1.05], [-2.2, 1.05] ]

inflation_layer:
  enabled:              true
  cost_scaling_factor:  1.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     3.5 # max. distance from an obstacle at which costs are incurred for planning paths.

obstacle_layer:
 enabled: true
 obstacle_range: 1.0
 raytrace_range: 3.5
 inflation_radius: 1.0
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {sensor_frame: navigation_lidars, data_type: LaserScan, topic: /merged_scan_navigation, marking: true, clearing: true}

 static_layer:
  enabled:              true
  map_topic:            "/map"


