
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [-2.2,-1.05], [2.2,-1.05], [2.2, 1.05], [-2.2, 1.05] ]
inflation_radius: 2.0

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: localization_lidars, data_type: LaserScan, topic: /merged_scan_localization, marking: true, clearing: true}

laser_scan_sensor: {sensor_frame: navigation_lidars, data_type: LaserScan, topic: /merged_scan_navigation, marking: true, clearing: true}

